version: '3.1'

services:

  db:
    image: mysql:8.0.22
    container_name: wordflow_db
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: example

  web:
    build: .
    container_name: wordflow_web
    volumes:
      - ./bedrock:/var/www/rocketstack
    ports:
      - "80:80"
      - "443:443"
